export enum PermissionsEnum {
  // User Module
  READ_USER = 'READ_USER',
  CREATE_USER = 'CREATE_USER',
  DELETE_USER = 'DELETE_USER',
  UPDATE_USER = 'UPDATE_USER',

  // Product Module
  READ_PRODUCT = 'READ_PRODUCT',
  CREATE_PRODUCT = 'CREATE_PRODUCT',
  DELETE_PRODUCT = 'DELETE_PRODUCT',
  UPDATE_PRODUCT = 'UPDATE_PRODUCT',

  // Order Module
  READ_ORDER = 'READ_ORDER',
  CREATE_ORDER = 'CREATE_ORDER',
  DELETE_ORDER = 'DELETE_ORDER',
  UPDATE_ORDER = 'UPDATE_ORDER',

  //Cart Module
  READ_CART = 'READ_CART',
  CREATE_CART = 'CREATE_CART',
  DELETE_CART = 'DELETE_CART',
  UPDATE_CART = 'UPDATE_CART',

  // Permission Module
  READ_PERMISSION = 'READ_PERMISSION',
  CREATE_PERMISSION = 'CREATE_PERMISSION',
  DELETE_PERMISSION = 'DELETE_PERMISSION',
  UPDATE_PERMISSION = 'UPDATE_PERMISSION',

  // Role Module
  READ_ROLE = 'READ_ROLE',
  CREATE_ROLE = 'CREATE_ROLE',
  DELETE_ROLE = 'DELETE_ROLE',
  UPDATE_ROLE = 'UPDATE_ROLE',

  // Category Module
  READ_CATEGORY = 'READ_CATEGORY',
  CREATE_CATEGORY = 'CREATE_CATEGORY',
  DELETE_CATEGORY = 'DELETE_CATEGORY',
  UPDATE_CATEGORY = 'UPDATE_CATEGORY',

  // Brand Module
  READ_BRAND = 'READ_BRAND',
  CREATE_BRAND = 'CREATE_BRAND',
  DELETE_BRAND = 'DELETE_BRAND',
  UPDATE_BRAND = 'UPDATE_BRAND',
}
